
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
const __dirname = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/library"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Audit_log_entries
 * const audit_log_entries = await prisma.audit_log_entries.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname)
export type PrismaClient<ClientOptions extends Prisma.PrismaClientOptions = Prisma.PrismaClientOptions, Log = $Class.LogOptions<ClientOptions>, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<ClientOptions, Log, ExtArgs>
export { Prisma }


// file annotations for bundling tools to include these files
path.join(__dirname, "libquery_engine-darwin-arm64.dylib.node")
path.join(process.cwd(), ".prisma/libquery_engine-darwin-arm64.dylib.node")

// file annotations for bundling tools to include these files
path.join(__dirname, "libquery_engine-debian-openssl-3.0.x.so.node")
path.join(process.cwd(), ".prisma/libquery_engine-debian-openssl-3.0.x.so.node")

/**
 * Model audit_log_entries
 * 
 */
export type audit_log_entries = Prisma.audit_log_entriesModel
/**
 * Model identities
 * 
 */
export type identities = Prisma.identitiesModel
/**
 * Model instances
 * 
 */
export type instances = Prisma.instancesModel
/**
 * Model mfa_amr_claims
 * 
 */
export type mfa_amr_claims = Prisma.mfa_amr_claimsModel
/**
 * Model mfa_challenges
 * 
 */
export type mfa_challenges = Prisma.mfa_challengesModel
/**
 * Model mfa_factors
 * 
 */
export type mfa_factors = Prisma.mfa_factorsModel
/**
 * Model refresh_tokens
 * 
 */
export type refresh_tokens = Prisma.refresh_tokensModel
/**
 * Model saml_providers
 * 
 */
export type saml_providers = Prisma.saml_providersModel
/**
 * Model saml_relay_states
 * 
 */
export type saml_relay_states = Prisma.saml_relay_statesModel
/**
 * Model schema_migrations
 * 
 */
export type schema_migrations = Prisma.schema_migrationsModel
/**
 * Model sessions
 * 
 */
export type sessions = Prisma.sessionsModel
/**
 * Model sso_domains
 * This model contains an expression index which requires additional setup for migrations. Visit https://pris.ly/d/expression-indexes for more info.
 */
export type sso_domains = Prisma.sso_domainsModel
/**
 * Model sso_providers
 * This model contains an expression index which requires additional setup for migrations. Visit https://pris.ly/d/expression-indexes for more info.
 */
export type sso_providers = Prisma.sso_providersModel
/**
 * Model users
 * This model contains an expression index which requires additional setup for migrations. Visit https://pris.ly/d/expression-indexes for more info.
 */
export type users = Prisma.usersModel
/**
 * Model flow_state
 * 
 */
export type flow_state = Prisma.flow_stateModel
/**
 * Model OrgsUsers
 * 
 */
export type OrgsUsers = Prisma.OrgsUsersModel
/**
 * Model OrgInviteLink
 * 
 */
export type OrgInviteLink = Prisma.OrgInviteLinkModel
/**
 * Model Org
 * 
 */
export type Org = Prisma.OrgModel
/**
 * Model ScrapedWebsitePage
 * 
 */
export type ScrapedWebsitePage = Prisma.ScrapedWebsitePageModel
/**
 * Model FramerLoginSession
 * 
 */
export type FramerLoginSession = Prisma.FramerLoginSessionModel
/**
 * Model GithubInstallation
 * 
 */
export type GithubInstallation = Prisma.GithubInstallationModel
/**
 * Model PaymentForCredits
 * 
 */
export type PaymentForCredits = Prisma.PaymentForCreditsModel
/**
 * Model Generation
 * 
 */
export type Generation = Prisma.GenerationModel
/**
 * Model Subscription
 * 
 */
export type Subscription = Prisma.SubscriptionModel
/**
 * Model one_time_tokens
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type one_time_tokens = Prisma.one_time_tokensModel
/**
 * Model GitHubSync
 * 
 */
export type GitHubSync = Prisma.GitHubSyncModel
/**
 * Model ReactExportProject
 * 
 */
export type ReactExportProject = Prisma.ReactExportProjectModel
/**
 * Model ReactExportComponent
 * 
 */
export type ReactExportComponent = Prisma.ReactExportComponentModel
/**
 * Model ReactExportCodeComponent
 * 
 */
export type ReactExportCodeComponent = Prisma.ReactExportCodeComponentModel
/**
 * Model ReactExportComponentBreakpoint
 * 
 */
export type ReactExportComponentBreakpoint = Prisma.ReactExportComponentBreakpointModel
/**
 * Model ReactExportComponentInstance
 * 
 */
export type ReactExportComponentInstance = Prisma.ReactExportComponentInstanceModel
/**
 * Model ReactExportWebPage
 * 
 */
export type ReactExportWebPage = Prisma.ReactExportWebPageModel
/**
 * Model ReactExportLocale
 * 
 */
export type ReactExportLocale = Prisma.ReactExportLocaleModel
/**
 * Model ReactExportColorStyle
 * 
 */
export type ReactExportColorStyle = Prisma.ReactExportColorStyleModel
/**
 * Model GitHubSyncedFile
 * 
 */
export type GitHubSyncedFile = Prisma.GitHubSyncedFileModel
/**
 * Model AngledScreenImagesGenerated
 * 
 */
export type AngledScreenImagesGenerated = Prisma.AngledScreenImagesGeneratedModel

export type GenerationStatus = $Enums.GenerationStatus
export const GenerationStatus = $Enums.GenerationStatus

export type GithubAccountType = $Enums.GithubAccountType
export const GithubAccountType = $Enums.GithubAccountType

export type UserRole = $Enums.UserRole
export const UserRole = $Enums.UserRole

export type PaymentProvider = $Enums.PaymentProvider
export const PaymentProvider = $Enums.PaymentProvider

export type SubscriptionStatus = $Enums.SubscriptionStatus
export const SubscriptionStatus = $Enums.SubscriptionStatus

export type aal_level = $Enums.aal_level
export const aal_level = $Enums.aal_level

export type factor_status = $Enums.factor_status
export const factor_status = $Enums.factor_status

export type factor_type = $Enums.factor_type
export const factor_type = $Enums.factor_type

export type code_challenge_method = $Enums.code_challenge_method
export const code_challenge_method = $Enums.code_challenge_method

export type one_time_token_type = $Enums.one_time_token_type
export const one_time_token_type = $Enums.one_time_token_type

export type PluginName = $Enums.PluginName
export const PluginName = $Enums.PluginName
