// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 620e74c088cdcb26 "Unframer Home Page", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Laptop' | 'Tablet' | 'Mobile' // Variant
 * terms?: string // terms
 * policy?: string // policy
 * login?: string // login
 * year?: string // year
}} Props

 */
import { Icon, stdin_default } from "./chunks/chunk-K6UQ5WSB.js";
import "./chunks/chunk-BVM6H744.js";
import { routes } from "./chunks/chunk-H4HRWUSE.js";

// virtual:footer
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/4hSUonWzpSrtZd1BhZvI/dM3eH9lbnopkuRZ5e9Ou/JHOLsHwUh.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/A6CsajQJnG9pUkwZlatc/L48pimMNsc6uDEEqWtZG/jqK_GhKTO.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getPropertyControls,
	Link,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var FeatherFonts = getFonts(Icon);
var FeatherControls = getPropertyControls(Icon);
var enabledGestures = {
	Qt8uCYS0y: {
		hover: true,
	},
};
var cycleOrder = ["Qt8uCYS0y"];
var serializationHash = "framer-Salbw";
var variantClassNames = {
	Qt8uCYS0y: "framer-v-k4www4",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableEnumMap = {
	"Alert-circle": "alert-circle",
	"Alert-octagon": "alert-octagon",
	"Alert-triangle": "alert-triangle",
	"Align-center": "align-center",
	"Align-justify": "align-justify",
	"Align-left": "align-left",
	"Align-right": "align-right",
	"Arrow-down-circle": "arrow-down-circle",
	"Arrow-down-left": "arrow-down-left",
	"Arrow-down-right": "arrow-down-right",
	"Arrow-down": "arrow-down",
	"Arrow-left-circle": "arrow-left-circle",
	"Arrow-left": "arrow-left",
	"Arrow-right-circle": "arrow-right-circle",
	"Arrow-right": "arrow-right",
	"Arrow-up-circle": "arrow-up-circle",
	"Arrow-up-left": "arrow-up-left",
	"Arrow-up-right": "arrow-up-right",
	"Arrow-up": "arrow-up",
	"At-sign": "at-sign",
	"Bar-chart-2": "bar-chart-2",
	"Bar-chart": "bar-chart",
	"Battery-charging": "battery-charging",
	"Bell-off": "bell-off",
	"Book-open": "book-open",
	"Camera-off": "camera-off",
	"Check-circle": "check-circle",
	"Check-square": "check-square",
	"Chevron-down": "chevron-down",
	"Chevron-left": "chevron-left",
	"Chevron-right": "chevron-right",
	"Chevron-up": "chevron-up",
	"Chevrons-down": "chevrons-down",
	"Chevrons-left": "chevrons-left",
	"Chevrons-right": "chevrons-right",
	"Chevrons-up": "chevrons-up",
	"Cloud-drizzle": "cloud-drizzle",
	"Cloud-lightning": "cloud-lightning",
	"Cloud-off": "cloud-off",
	"Cloud-rain": "cloud-rain",
	"Cloud-snow": "cloud-snow",
	"Corner-down-left": "corner-down-left",
	"Corner-down-right": "corner-down-right",
	"Corner-left-down": "corner-left-down",
	"Corner-left-up": "corner-left-up",
	"Corner-right-down": "corner-right-down",
	"Corner-right-up": "corner-right-up",
	"Corner-up-left": "corner-up-left",
	"Corner-up-right": "corner-up-right",
	"Credit-card": "credit-card",
	"Divide-circle": "divide-circle",
	"Divide-square": "divide-square",
	"Dollar-sign": "dollar-sign",
	"Download-cloud": "download-cloud",
	"Edit-2": "edit-2",
	"Edit-3": "edit-3",
	"External-link": "external-link",
	"Eye-off": "eye-off",
	"Fast-forward": "fast-forward",
	"File-minus": "file-minus",
	"File-plus": "file-plus",
	"File-text": "file-text",
	"Folder-minus": "folder-minus",
	"Folder-plus": "folder-plus",
	"Git-branch": "git-branch",
	"Git-commit": "git-commit",
	"Git-merge": "git-merge",
	"Git-pull-request": "git-pull-request",
	"Hard-drive": "hard-drive",
	"Help-circle": "help-circle",
	"Life-buoy": "life-buoy",
	"Link-2": "link-2",
	"Log-in": "log-in",
	"Log-out": "log-out",
	"Map-pin": "map-pin",
	"Maximize-2": "maximize-2",
	"Message-circle": "message-circle",
	"Message-square": "message-square",
	"Mic-off": "mic-off",
	"Minimize-2": "minimize-2",
	"Minus-circle": "minus-circle",
	"Minus-square": "minus-square",
	"More-horizontal": "more-horizontal",
	"More-vertical": "more-vertical",
	"Mouse-pointer": "mouse-pointer",
	"Navigation-2": "navigation-2",
	"Pause-circle": "pause-circle",
	"Pen-tool": "pen-tool",
	"Phone-call": "phone-call",
	"Phone-forwarded": "phone-forwarded",
	"Phone-incoming": "phone-incoming",
	"Phone-missed": "phone-missed",
	"Phone-off": "phone-off",
	"Phone-outgoing": "phone-outgoing",
	"Pie-chart": "pie-chart",
	"Play-circle": "play-circle",
	"Plus-circle": "plus-circle",
	"Plus-square": "plus-square",
	"Refresh-ccw": "refresh-ccw",
	"Refresh-cw": "refresh-cw",
	"Rotate-ccw": "rotate-ccw",
	"Rotate-cw": "rotate-cw",
	"Share-2": "share-2",
	"Shield-off": "shield-off",
	"Shopping-bag": "shopping-bag",
	"Shopping-cart": "shopping-cart",
	"Skip-back": "skip-back",
	"Skip-forward": "skip-forward",
	"Stop-circle": "stop-circle",
	"Thumbs-down": "thumbs-down",
	"Thumbs-up": "thumbs-up",
	"Toggle-left": "toggle-left",
	"Toggle-right": "toggle-right",
	"Trash-2": "trash-2",
	"Trending-down": "trending-down",
	"Trending-up": "trending-up",
	"Upload-cloud": "upload-cloud",
	"User-check": "user-check",
	"User-minus": "user-minus",
	"User-plus": "user-plus",
	"User-x": "user-x",
	"Video-off": "video-off",
	"Volume-1": "volume-1",
	"Volume-2": "volume-2",
	"Volume-x": "volume-x",
	"Wifi-off": "wifi-off",
	"X-circle": "x-circle",
	"X-octagon": "x-octagon",
	"X-square": "x-square",
	"Zap-off": "zap-off",
	"Zoom-in": "zoom-in",
	"Zoom-out": "zoom-out",
	Activity: "activity",
	Airplay: "airplay",
	Anchor: "anchor",
	Aperture: "aperture",
	Archive: "archive",
	Award: "award",
	Battery: "battery",
	Bell: "bell",
	Bluetooth: "bluetooth",
	Bold: "bold",
	Book: "book",
	Bookmark: "bookmark",
	Box: "box",
	Briefcase: "briefcase",
	Calendar: "calendar",
	Camera: "camera",
	Cast: "cast",
	Check: "check",
	Chrome: "chrome",
	Circle: "circle",
	Clipboard: "clipboard",
	Clock: "clock",
	Cloud: "cloud",
	Code: "code",
	Codepen: "codepen",
	Codesandbox: "codesandbox",
	Coffee: "coffee",
	Columns: "columns",
	Command: "command",
	Compass: "compass",
	Copy: "copy",
	Cpu: "cpu",
	Crop: "crop",
	Crosshair: "crosshair",
	Database: "database",
	Delete: "delete",
	Disc: "disc",
	Divide: "divide",
	Download: "download",
	Dribbble: "dribbble",
	Droplet: "droplet",
	Edit: "edit",
	Eye: "eye",
	Facebook: "facebook",
	Feather: "feather",
	Figma: "figma",
	File: "file",
	Film: "film",
	Filter: "filter",
	Flag: "flag",
	Folder: "folder",
	Framer: "framer",
	Frown: "frown",
	Gift: "gift",
	Github: "github",
	Gitlab: "gitlab",
	Globe: "globe",
	Grid: "grid",
	Hash: "hash",
	Headphones: "headphones",
	Heart: "heart",
	Hexagon: "hexagon",
	Home: "home",
	Image: "image",
	Inbox: "inbox",
	Info: "info",
	Instagram: "instagram",
	Italic: "italic",
	Key: "key",
	Layers: "layers",
	Layout: "layout",
	Link: "link",
	Linkedin: "linkedin",
	List: "list",
	Loader: "loader",
	Lock: "lock",
	Mail: "mail",
	Map: "map",
	Maximize: "maximize",
	Meh: "meh",
	Menu: "menu",
	Mic: "mic",
	Minimize: "minimize",
	Minus: "minus",
	Monitor: "monitor",
	Moon: "moon",
	Move: "move",
	Music: "music",
	Navigation: "navigation",
	Octagon: "octagon",
	Package: "package",
	Paperclip: "paperclip",
	Pause: "pause",
	Percent: "percent",
	Phone: "phone",
	Play: "play",
	Plus: "plus",
	Pocket: "pocket",
	Power: "power",
	Printer: "printer",
	Radio: "radio",
	Repeat: "repeat",
	Rewind: "rewind",
	Rss: "rss",
	Save: "save",
	Scissors: "scissors",
	Search: "search",
	Send: "send",
	Server: "server",
	Settings: "settings",
	Share: "share",
	Shield: "shield",
	Shuffle: "shuffle",
	Sidebar: "sidebar",
	Slack: "slack",
	Slash: "slash",
	Sliders: "sliders",
	Smartphone: "smartphone",
	Smile: "smile",
	Speaker: "speaker",
	Square: "square",
	Star: "star",
	Sun: "sun",
	Sunrise: "sunrise",
	Sunset: "sunset",
	Tablet: "tablet",
	Tag: "tag",
	Target: "target",
	Terminal: "terminal",
	Thermometer: "thermometer",
	Tool: "tool",
	Trash: "trash",
	Trello: "trello",
	Triangle: "triangle",
	Truck: "truck",
	Tv: "tv",
	Twitch: "twitch",
	Twitter: "twitter",
	Type: "type",
	Umbrella: "umbrella",
	Underline: "underline",
	Unlock: "unlock",
	Upload: "upload",
	User: "user",
	Users: "users",
	Video: "video",
	Voicemail: "voicemail",
	Volume: "volume",
	Watch: "watch",
	Wifi: "wifi",
	Wind: "wind",
	X: "x",
	Youtube: "youtube",
	Zap: "zap",
};
var getProps = ({ height, id, link, name1, width, ...props }) => {
	var _humanReadableEnumMap_name1, _ref, _ref1;
	return {
		...props,
		AtQ5PEj2x: link !== null && link !== void 0 ? link : props.AtQ5PEj2x,
		f6skm2rkz:
			(_ref1 =
				(_ref =
					(_humanReadableEnumMap_name1 = humanReadableEnumMap[name1]) !==
						null && _humanReadableEnumMap_name1 !== void 0
						? _humanReadableEnumMap_name1
						: name1) !== null && _ref !== void 0
					? _ref
					: props.f6skm2rkz) !== null && _ref1 !== void 0
				? _ref1
				: "facebook",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		f6skm2rkz,
		AtQ5PEj2x,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Qt8uCYS0y",
		enabledGestures,
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition}>
					<Link href={AtQ5PEj2x}>
						<motion.a
							{...restProps}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-k4www4", className, classNames)} framer-1ft1x0s`}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"Qt8uCYS0y"}
							onHoverEnd={() =>
								setGestureState({
									isHovered: false,
								})
							}
							onHoverStart={() =>
								setGestureState({
									isHovered: true,
								})
							}
							onTap={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapCancel={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapStart={() =>
								setGestureState({
									isPressed: true,
								})
							}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"Qt8uCYS0y-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<ComponentViewportProvider>
								<motion.div
									className={"framer-jrb1he-container"}
									layoutDependency={layoutDependency}
									layoutId={"I4X5WKxaL-container"}
								>
									<Icon
										color={
											"var(--token-b50174c0-f355-49d1-a882-48c9e51b5466, rgb(255, 255, 255))"
										}
										height={"100%"}
										iconSearch={"Home"}
										iconSelection={f6skm2rkz}
										id={"I4X5WKxaL"}
										layoutId={"I4X5WKxaL"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
										{...addPropertyOverrides(
											{
												"Qt8uCYS0y-hover": {
													color:
														"var(--token-a05655a1-e6dd-4d69-a82a-f5054b601f79, rgb(193, 255, 86))",
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
							</ComponentViewportProvider>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	'.framer-Salbw[data-border="true"]::after, .framer-Salbw [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Salbw.framer-1ft1x0s, .framer-Salbw .framer-1ft1x0s { display: block; }",
	".framer-Salbw.framer-k4www4 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 24px; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; text-decoration: none; width: 24px; }",
	".framer-Salbw .framer-jrb1he-container { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Salbw.framer-k4www4 { gap: 0px; } .framer-Salbw.framer-k4www4 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-Salbw.framer-k4www4 > :first-child { margin-left: 0px; } .framer-Salbw.framer-k4www4 > :last-child { margin-right: 0px; } }",
];
var FramerjqK_GhKTO = withCSS(Component, css, "framer-Salbw");
var stdin_default2 = FramerjqK_GhKTO;
FramerjqK_GhKTO.displayName = "Social icon";
FramerjqK_GhKTO.defaultProps = {
	height: 24,
	width: 24,
};
addPropertyControls(FramerjqK_GhKTO, {
	f6skm2rkz: (FeatherControls === null || FeatherControls === void 0
		? void 0
		: FeatherControls["iconSelection"]) && {
		...FeatherControls["iconSelection"],
		defaultValue: "facebook",
		description: void 0,
		hidden: void 0,
		title: "Name",
	},
	AtQ5PEj2x: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(FramerjqK_GhKTO, [...FeatherFonts]);

// /:https://framerusercontent.com/modules/4hSUonWzpSrtZd1BhZvI/dM3eH9lbnopkuRZ5e9Ou/JHOLsHwUh.js
var SocialIconFonts = getFonts2(stdin_default2);
var NavItemFonts = getFonts2(stdin_default);
var cycleOrder2 = ["GDQSlkfkE", "qIAmRE5Sc", "jwF72UoRb", "DqztAW3Uf"];
var serializationHash2 = "framer-8Xhvr";
var variantClassNames2 = {
	DqztAW3Uf: "framer-v-kunx44",
	GDQSlkfkE: "framer-v-qrs14q",
	jwF72UoRb: "framer-v-whwe5s",
	qIAmRE5Sc: "framer-v-9ydk7y",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	Desktop: "GDQSlkfkE",
	Laptop: "qIAmRE5Sc",
	Mobile: "DqztAW3Uf",
	Tablet: "jwF72UoRb",
};
var getProps2 = ({
	height,
	id,
	login,
	policy,
	terms,
	width,
	year,
	...props
}) => {
	return {
		...props,
		burzVaCmv: year ?? props.burzVaCmv ?? "2024",
		CdD29hsWO: policy ?? props.CdD29hsWO,
		JQRTkRRgY: terms ?? props.JQRTkRRgY,
		KsiLB1lNU: login ?? props.KsiLB1lNU,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "GDQSlkfkE",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className,
		layoutId,
		variant,
		JQRTkRRgY,
		CdD29hsWO,
		KsiLB1lNU,
		burzVaCmv,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "GDQSlkfkE",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-qrs14q",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"GDQSlkfkE"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								DqztAW3Uf: {
									"data-framer-name": "Mobile",
								},
								jwF72UoRb: {
									"data-framer-name": "Tablet",
								},
								qIAmRE5Sc: {
									"data-framer-name": "Laptop",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1oh9v1q"}
							data-framer-name={"Top content"}
							layoutDependency={layoutDependency}
							layoutId={"cOjtPg93y"}
						>
							<motion2.div
								className={"framer-eux8tn"}
								data-framer-name={"Left"}
								layoutDependency={layoutDependency}
								layoutId={"iuhWxmIjH"}
							>
								<motion2.div
									className={"framer-o2tak5"}
									data-framer-name={"Logo & Text"}
									layoutDependency={layoutDependency}
									layoutId={"Ri4leVcBa"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1l4n3g0"}
										data-framer-name={
											"Secure, transparent transfer of data and value without centralized control. Building blocks for Web3 and metaverse"
										}
										fonts={["GF;Space Grotesk-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"OOxXQW4Zg"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-b50174c0-f355-49d1-a882-48c9e51b5466, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
											opacity: 0.6,
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides2(
											{
												DqztAW3Uf: {
													children: (
														<React2.Fragment>
															<motion2.p
																style={{
																	"--font-selector":
																		"R0Y7U3BhY2UgR3JvdGVzay1yZWd1bGFy",
																	"--framer-font-family":
																		'"Space Grotesk", "Space Grotesk Placeholder", sans-serif',
																	"--framer-line-height": "1.7em",
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-b50174c0-f355-49d1-a882-48c9e51b5466, rgb(255, 255, 255)))",
																}}
															>
																{"Powerful plugins for Framer"}
															</motion2.p>
														</React2.Fragment>
													),
												},
												jwF72UoRb: {
													children: (
														<React2.Fragment>
															<motion2.p
																style={{
																	"--font-selector":
																		"R0Y7U3BhY2UgR3JvdGVzay1yZWd1bGFy",
																	"--framer-font-family":
																		'"Space Grotesk", "Space Grotesk Placeholder", sans-serif',
																	"--framer-line-height": "1.7em",
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-b50174c0-f355-49d1-a882-48c9e51b5466, rgb(255, 255, 255)))",
																}}
															>
																{"Powerful plugins for Framer"}
															</motion2.p>
														</React2.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React2.Fragment>
											<motion2.p
												style={{
													"--font-selector": "R0Y7U3BhY2UgR3JvdGVzay1yZWd1bGFy",
													"--framer-font-family":
														'"Space Grotesk", "Space Grotesk Placeholder", sans-serif',
													"--framer-line-height": "1.7em",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-b50174c0-f355-49d1-a882-48c9e51b5466, rgb(255, 255, 255)))",
												}}
											>
												{"Powerful plugins for Framer"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
								<motion2.div
									className={"framer-13hu3vh"}
									data-framer-name={"Social"}
									layoutDependency={layoutDependency}
									layoutId={"D2cx1hPSn"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-ahuxuc"}
										data-framer-name={"Connect with:"}
										fonts={["GF;Space Grotesk-500"]}
										layoutDependency={layoutDependency}
										layoutId={"lG2NJhMjN"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-c46c0c2d-e53e-42e7-8f54-be852f62337f, rgb(224, 232, 210))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												style={{
													"--font-selector": "R0Y7U3BhY2UgR3JvdGVzay01MDA=",
													"--framer-font-family":
														'"Space Grotesk", "Space Grotesk Placeholder", sans-serif',
													"--framer-font-weight": "500",
													"--framer-line-height": "1.7em",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-c46c0c2d-e53e-42e7-8f54-be852f62337f, rgb(224, 232, 210)))",
												}}
											>
												{"Connect with:"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
									<motion2.div
										className={"framer-fjt036"}
										data-framer-name={"Social Links"}
										layoutDependency={layoutDependency}
										layoutId={"dD5LhILPx"}
									>
										<ComponentViewportProvider2
											height={24}
											width={"24px"}
											y={
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 202) - 0 - 299.2) / 2 +
													0 +
													0) +
												0 +
												0 +
												0 +
												168 +
												0 +
												35.2 +
												0
											}
											{...addPropertyOverrides2(
												{
													DqztAW3Uf: {
														y:
															(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 708) -
																0 -
																815.2) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															176 +
															0 +
															47.2 +
															0,
													},
													jwF72UoRb: {
														y:
															(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 500) -
																0 -
																608.2) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															176 +
															0 +
															47.2 +
															0,
													},
													qIAmRE5Sc: {
														y:
															(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 352) -
																0 -
																449.2) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															168 +
															0 +
															35.2 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-jb4gv8-container"}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"kTQTdv_G8-container"}
												nodeId={"kTQTdv_G8"}
												rendersWithMotion={true}
												scopeId={"JHOLsHwUh"}
											>
												{_jsx2(stdin_default2, {
													AtQ5PEj2x: "https://twitter.com/__morse",
													f6skm2rkz: "twitter",
													height: "100%",
													id: "kTQTdv_G8",
													layoutId: "kTQTdv_G8",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider2>
									</motion2.div>
								</motion2.div>
							</motion2.div>
							<motion2.div
								className={"framer-16mwtoh"}
								data-framer-name={"Texts"}
								layoutDependency={layoutDependency}
								layoutId={"CU_VwdaVh"}
							>
								<motion2.div
									className={"framer-1hqqt7y"}
									data-framer-name={"Linkes"}
									layoutDependency={layoutDependency}
									layoutId={"Ud6FfZFfH"}
								>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "augiA20Il",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "augiA20Il",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "augiA20Il",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "augiA20Il",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider2
												height={27}
												y={
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 202) - 0 - 299.2) /
														2 +
														0 +
														0) +
													0 +
													98.2 +
													0 +
													0 +
													0
												}
												{...addPropertyOverrides2(
													{
														DqztAW3Uf: {
															y:
																(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 708) -
																	0 -
																	815.2) /
																	2 +
																	0 +
																	0) +
																0 +
																282.2 +
																0 +
																0 +
																0 +
																0,
														},
														jwF72UoRb: {
															y:
																(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 500) -
																	0 -
																	608.2) /
																	2 +
																	0 +
																	0) +
																0 +
																307.2 +
																0 +
																0 +
																0,
														},
														qIAmRE5Sc: {
															y:
																(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 352) -
																	0 -
																	449.2) /
																	2 +
																	0 +
																	0) +
																0 +
																98.2 +
																0 +
																0 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-x9gtqy-container"}
													layoutDependency={layoutDependency}
													layoutId={"XhOYXoqlI-container"}
													nodeId={"XhOYXoqlI"}
													rendersWithMotion={true}
													scopeId={"JHOLsHwUh"}
												>
													{_jsx2(stdin_default, {
														cRqRWoih6: resolvedLinks[0],
														height: "100%",
														id: "XhOYXoqlI",
														layoutId: "XhOYXoqlI",
														Oc0fzh3x0: false,
														okFfDCMAr: "Features",
														width: "100%",
														...addPropertyOverrides2(
															{
																DqztAW3Uf: {
																	cRqRWoih6: resolvedLinks[3],
																},
																jwF72UoRb: {
																	cRqRWoih6: resolvedLinks[2],
																},
																qIAmRE5Sc: {
																	cRqRWoih6: resolvedLinks[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider2>
										)}
									</ResolveLinks>
									<ComponentViewportProvider2
										height={27}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 202) - 0 - 299.2) / 2 +
												0 +
												0) +
											0 +
											98.2 +
											0 +
											0 +
											51
										}
										{...addPropertyOverrides2(
											{
												DqztAW3Uf: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 708) - 0 - 815.2) /
															2 +
															0 +
															0) +
														0 +
														282.2 +
														0 +
														0 +
														0 +
														51,
												},
												jwF72UoRb: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 500) - 0 - 608.2) /
															2 +
															0 +
															0) +
														0 +
														307.2 +
														0 +
														0 +
														51,
												},
												qIAmRE5Sc: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 352) - 0 - 449.2) /
															2 +
															0 +
															0) +
														0 +
														98.2 +
														0 +
														0 +
														51,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-14bqoja-container"}
											layoutDependency={layoutDependency}
											layoutId={"dW3RCLde3-container"}
											nodeId={"dW3RCLde3"}
											rendersWithMotion={true}
											scopeId={"JHOLsHwUh"}
										>
											{_jsx2(stdin_default, {
												cRqRWoih6: "https://twitter.com/__morse",
												height: "100%",
												id: "dW3RCLde3",
												layoutId: "dW3RCLde3",
												Oc0fzh3x0: false,
												okFfDCMAr: "About",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider2>
								</motion2.div>
								<motion2.div
									className={"framer-erelaw"}
									data-framer-name={"Linkes"}
									layoutDependency={layoutDependency}
									layoutId={"s3it5KWGe"}
								>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "A2nW9HZFd",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "A2nW9HZFd",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "A2nW9HZFd",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "A2nW9HZFd",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks1) => (
											<ComponentViewportProvider2
												height={27}
												y={
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 202) - 0 - 299.2) /
														2 +
														0 +
														0) +
													0 +
													98.2 +
													0 +
													0 +
													0
												}
												{...addPropertyOverrides2(
													{
														DqztAW3Uf: {
															y:
																(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 708) -
																	0 -
																	815.2) /
																	2 +
																	0 +
																	0) +
																0 +
																282.2 +
																0 +
																108 +
																0 +
																0,
														},
														jwF72UoRb: {
															y:
																(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 500) -
																	0 -
																	608.2) /
																	2 +
																	0 +
																	0) +
																0 +
																307.2 +
																0 +
																0 +
																0,
														},
														qIAmRE5Sc: {
															y:
																(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 352) -
																	0 -
																	449.2) /
																	2 +
																	0 +
																	0) +
																0 +
																98.2 +
																0 +
																0 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-1pmuhti-container"}
													layoutDependency={layoutDependency}
													layoutId={"h_zUpaUz6-container"}
													nodeId={"h_zUpaUz6"}
													rendersWithMotion={true}
													scopeId={"JHOLsHwUh"}
												>
													{_jsx2(stdin_default, {
														cRqRWoih6: resolvedLinks1[0],
														height: "100%",
														id: "h_zUpaUz6",
														layoutId: "h_zUpaUz6",
														Oc0fzh3x0: false,
														okFfDCMAr: "Contact Us",
														width: "100%",
														...addPropertyOverrides2(
															{
																DqztAW3Uf: {
																	cRqRWoih6: resolvedLinks1[3],
																},
																jwF72UoRb: {
																	cRqRWoih6: resolvedLinks1[2],
																},
																qIAmRE5Sc: {
																	cRqRWoih6: resolvedLinks1[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider2>
										)}
									</ResolveLinks>
									<ComponentViewportProvider2
										height={27}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 202) - 0 - 299.2) / 2 +
												0 +
												0) +
											0 +
											98.2 +
											0 +
											0 +
											51
										}
										{...addPropertyOverrides2(
											{
												DqztAW3Uf: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 708) - 0 - 815.2) /
															2 +
															0 +
															0) +
														0 +
														282.2 +
														0 +
														108 +
														0 +
														51,
												},
												jwF72UoRb: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 500) - 0 - 608.2) /
															2 +
															0 +
															0) +
														0 +
														307.2 +
														0 +
														0 +
														51,
												},
												qIAmRE5Sc: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 352) - 0 - 449.2) /
															2 +
															0 +
															0) +
														0 +
														98.2 +
														0 +
														0 +
														51,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-my5pq1-container"}
											layoutDependency={layoutDependency}
											layoutId={"FtUF1nNyk-container"}
											nodeId={"FtUF1nNyk"}
											rendersWithMotion={true}
											scopeId={"JHOLsHwUh"}
										>
											{_jsx2(stdin_default, {
												cRqRWoih6: JQRTkRRgY,
												height: "100%",
												id: "FtUF1nNyk",
												layoutId: "FtUF1nNyk",
												Oc0fzh3x0: false,
												okFfDCMAr: "Terms & Conditions",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider2>
									<ComponentViewportProvider2
										height={27}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 202) - 0 - 299.2) / 2 +
												0 +
												0) +
											0 +
											98.2 +
											0 +
											0 +
											102
										}
										{...addPropertyOverrides2(
											{
												DqztAW3Uf: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 708) - 0 - 815.2) /
															2 +
															0 +
															0) +
														0 +
														282.2 +
														0 +
														108 +
														0 +
														102,
												},
												jwF72UoRb: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 500) - 0 - 608.2) /
															2 +
															0 +
															0) +
														0 +
														307.2 +
														0 +
														0 +
														102,
												},
												qIAmRE5Sc: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 352) - 0 - 449.2) /
															2 +
															0 +
															0) +
														0 +
														98.2 +
														0 +
														0 +
														102,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1qdworl-container"}
											layoutDependency={layoutDependency}
											layoutId={"qPsfIKeR4-container"}
											nodeId={"qPsfIKeR4"}
											rendersWithMotion={true}
											scopeId={"JHOLsHwUh"}
										>
											{_jsx2(stdin_default, {
												cRqRWoih6: CdD29hsWO,
												height: "100%",
												id: "qPsfIKeR4",
												layoutId: "qPsfIKeR4",
												Oc0fzh3x0: false,
												okFfDCMAr: "Privacy Policy",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider2>
								</motion2.div>
								<motion2.div
									className={"framer-1de5mf"}
									data-framer-name={"Linkes"}
									layoutDependency={layoutDependency}
									layoutId={"tpAZRYt7C"}
								>
									<ComponentViewportProvider2
										height={27}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 202) - 0 - 299.2) / 2 +
												0 +
												0) +
											0 +
											98.2 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides2(
											{
												DqztAW3Uf: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 708) - 0 - 815.2) /
															2 +
															0 +
															0) +
														0 +
														282.2 +
														0 +
														267 +
														0 +
														0,
												},
												jwF72UoRb: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 500) - 0 - 608.2) /
															2 +
															0 +
															0) +
														0 +
														307.2 +
														0 +
														0 +
														0,
												},
												qIAmRE5Sc: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 352) - 0 - 449.2) /
															2 +
															0 +
															0) +
														0 +
														98.2 +
														0 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1hucny5-container"}
											layoutDependency={layoutDependency}
											layoutId={"YzPLAUkNQ-container"}
											nodeId={"YzPLAUkNQ"}
											rendersWithMotion={true}
											scopeId={"JHOLsHwUh"}
										>
											{_jsx2(stdin_default, {
												cRqRWoih6: KsiLB1lNU,
												height: "100%",
												id: "YzPLAUkNQ",
												layoutId: "YzPLAUkNQ",
												Oc0fzh3x0: false,
												okFfDCMAr: "Manage Account",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider2>
									<ComponentViewportProvider2
										height={27}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 202) - 0 - 299.2) / 2 +
												0 +
												0) +
											0 +
											98.2 +
											0 +
											0 +
											51
										}
										{...addPropertyOverrides2(
											{
												DqztAW3Uf: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 708) - 0 - 815.2) /
															2 +
															0 +
															0) +
														0 +
														282.2 +
														0 +
														267 +
														0 +
														51,
												},
												jwF72UoRb: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 500) - 0 - 608.2) /
															2 +
															0 +
															0) +
														0 +
														307.2 +
														0 +
														0 +
														51,
												},
												qIAmRE5Sc: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 352) - 0 - 449.2) /
															2 +
															0 +
															0) +
														0 +
														98.2 +
														0 +
														0 +
														51,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1led324-container"}
											layoutDependency={layoutDependency}
											layoutId={"nVgj095cM-container"}
											nodeId={"nVgj095cM"}
											rendersWithMotion={true}
											scopeId={"JHOLsHwUh"}
										>
											{_jsx2(stdin_default, {
												cRqRWoih6: KsiLB1lNU,
												height: "100%",
												id: "nVgj095cM",
												layoutId: "nVgj095cM",
												Oc0fzh3x0: false,
												okFfDCMAr: "Manage Subscriptions",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider2>
									<ComponentViewportProvider2
										height={27}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 202) - 0 - 299.2) / 2 +
												0 +
												0) +
											0 +
											98.2 +
											0 +
											0 +
											102
										}
										{...addPropertyOverrides2(
											{
												DqztAW3Uf: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 708) - 0 - 815.2) /
															2 +
															0 +
															0) +
														0 +
														282.2 +
														0 +
														267 +
														0 +
														102,
												},
												jwF72UoRb: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 500) - 0 - 608.2) /
															2 +
															0 +
															0) +
														0 +
														307.2 +
														0 +
														0 +
														102,
												},
												qIAmRE5Sc: {
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 352) - 0 - 449.2) /
															2 +
															0 +
															0) +
														0 +
														98.2 +
														0 +
														0 +
														102,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-b8e6xq-container"}
											layoutDependency={layoutDependency}
											layoutId={"feDdGRHVx-container"}
											nodeId={"feDdGRHVx"}
											rendersWithMotion={true}
											scopeId={"JHOLsHwUh"}
										>
											{_jsx2(stdin_default, {
												cRqRWoih6: KsiLB1lNU,
												height: "100%",
												id: "feDdGRHVx",
												layoutId: "feDdGRHVx",
												Oc0fzh3x0: false,
												okFfDCMAr: "Login",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider2>
								</motion2.div>
							</motion2.div>
						</motion2.div>
						<motion2.div
							className={"framer-1n4oyel"}
							data-border={true}
							data-framer-name={"Bottom Content"}
							layoutDependency={layoutDependency}
							layoutId={"wWAUXHDTc"}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgba(255, 255, 255, 0.1)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "1px",
							}}
						>
							<motion2.div
								className={"framer-12t902f"}
								layoutDependency={layoutDependency}
								layoutId={"fVivPOIwE"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1dy0rei"}
									data-framer-name={"2024 \xA9 WebChain Copyright"}
									fonts={["GF;Space Grotesk-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"lTPG2_QWt"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-b50174c0-f355-49d1-a882-48c9e51b5466, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={burzVaCmv}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											style={{
												"--font-selector": "R0Y7U3BhY2UgR3JvdGVzay1yZWd1bGFy",
												"--framer-font-family":
													'"Space Grotesk", "Space Grotesk Placeholder", sans-serif',
												"--framer-font-size": "13px",
												"--framer-line-height": "1.7em",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-b50174c0-f355-49d1-a882-48c9e51b5466, rgb(255, 255, 255)))",
											}}
										>
											{"2024"}
										</motion2.p>
									</React2.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-glh8is"}
									data-framer-name={"2024 \xA9 WebChain Copyright"}
									fonts={["GF;Space Grotesk-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"FiW7nd0Zf"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-b50174c0-f355-49d1-a882-48c9e51b5466, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											style={{
												"--font-selector": "R0Y7U3BhY2UgR3JvdGVzay1yZWd1bGFy",
												"--framer-font-family":
													'"Space Grotesk", "Space Grotesk Placeholder", sans-serif',
												"--framer-font-size": "13px",
												"--framer-line-height": "1.7em",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-b50174c0-f355-49d1-a882-48c9e51b5466, rgb(255, 255, 255)))",
											}}
										>
											{"\xA9 Unframer Copyright"}
										</motion2.p>
									</React2.Fragment>
								</RichText>
							</motion2.div>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-8Xhvr.framer-1r1lxt2, .framer-8Xhvr .framer-1r1lxt2 { display: block; }",
	".framer-8Xhvr.framer-qrs14q { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 17px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1140px; }",
	".framer-8Xhvr .framer-1oh9v1q { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-8Xhvr .framer-eux8tn { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 32%; }",
	".framer-8Xhvr .framer-o2tak5 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-8Xhvr .framer-1l4n3g0 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-8Xhvr .framer-13hu3vh { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-8Xhvr .framer-ahuxuc, .framer-8Xhvr .framer-1dy0rei, .framer-8Xhvr .framer-glh8is { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-8Xhvr .framer-fjt036 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-8Xhvr .framer-jb4gv8-container { flex: none; height: 24px; position: relative; width: 24px; }",
	".framer-8Xhvr .framer-16mwtoh { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 52%; }",
	".framer-8Xhvr .framer-1hqqt7y, .framer-8Xhvr .framer-erelaw, .framer-8Xhvr .framer-1de5mf { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-8Xhvr .framer-x9gtqy-container, .framer-8Xhvr .framer-14bqoja-container, .framer-8Xhvr .framer-1pmuhti-container, .framer-8Xhvr .framer-my5pq1-container, .framer-8Xhvr .framer-1qdworl-container, .framer-8Xhvr .framer-1hucny5-container, .framer-8Xhvr .framer-1led324-container, .framer-8Xhvr .framer-b8e6xq-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-8Xhvr .framer-1n4oyel { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 11px 0px 17px 0px; position: relative; width: 100%; }",
	".framer-8Xhvr .framer-12t902f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: 27px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-8Xhvr.framer-v-9ydk7y.framer-qrs14q { gap: 80px; width: 932px; }",
	".framer-8Xhvr.framer-v-9ydk7y .framer-16mwtoh { width: 53%; }",
	".framer-8Xhvr.framer-v-9ydk7y .framer-1n4oyel { padding: 50px 0px 65px 0px; }",
	".framer-8Xhvr.framer-v-whwe5s.framer-qrs14q { gap: 65px; width: 708px; }",
	".framer-8Xhvr.framer-v-whwe5s .framer-1oh9v1q { flex-direction: column; gap: 60px; justify-content: center; }",
	".framer-8Xhvr.framer-v-whwe5s .framer-eux8tn, .framer-8Xhvr.framer-v-kunx44 .framer-eux8tn { align-content: center; align-items: center; gap: 40px; justify-content: center; width: 100%; }",
	".framer-8Xhvr.framer-v-whwe5s .framer-o2tak5, .framer-8Xhvr.framer-v-kunx44 .framer-o2tak5 { align-content: center; align-items: center; }",
	".framer-8Xhvr.framer-v-whwe5s .framer-1l4n3g0 { width: 75%; }",
	".framer-8Xhvr.framer-v-whwe5s .framer-13hu3vh, .framer-8Xhvr.framer-v-kunx44 .framer-13hu3vh { align-content: center; align-items: center; gap: 20px; }",
	".framer-8Xhvr.framer-v-whwe5s .framer-16mwtoh { width: 100%; }",
	".framer-8Xhvr.framer-v-whwe5s .framer-1hqqt7y, .framer-8Xhvr.framer-v-whwe5s .framer-erelaw, .framer-8Xhvr.framer-v-whwe5s .framer-1de5mf, .framer-8Xhvr.framer-v-kunx44 .framer-1hqqt7y, .framer-8Xhvr.framer-v-kunx44 .framer-erelaw, .framer-8Xhvr.framer-v-kunx44 .framer-1de5mf { align-content: center; align-items: center; justify-content: center; }",
	".framer-8Xhvr.framer-v-whwe5s .framer-1n4oyel { padding: 40px 0px 40px 0px; }",
	".framer-8Xhvr.framer-v-kunx44.framer-qrs14q { gap: 50px; width: 350px; }",
	".framer-8Xhvr.framer-v-kunx44 .framer-1oh9v1q { flex-direction: column; gap: 35px; justify-content: center; }",
	".framer-8Xhvr.framer-v-kunx44 .framer-16mwtoh { align-content: center; align-items: center; flex-direction: column; gap: 30px; justify-content: center; width: 100%; }",
	".framer-8Xhvr.framer-v-kunx44 .framer-1n4oyel { padding: 30px 0px 30px 0px; }",
	'.framer-8Xhvr[data-border="true"]::after, .framer-8Xhvr [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerJHOLsHwUh = withCSS2(Component2, css2, "framer-8Xhvr");
var stdin_default3 = FramerJHOLsHwUh;
FramerJHOLsHwUh.displayName = "Footer";
FramerJHOLsHwUh.defaultProps = {
	height: 202,
	width: 1140,
};
addPropertyControls2(FramerJHOLsHwUh, {
	variant: {
		options: ["GDQSlkfkE", "qIAmRE5Sc", "jwF72UoRb", "DqztAW3Uf"],
		optionTitles: ["Desktop", "Laptop", "Tablet", "Mobile"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	JQRTkRRgY: {
		title: "terms",
		type: ControlType2.Link,
	},
	CdD29hsWO: {
		title: "policy",
		type: ControlType2.Link,
	},
	KsiLB1lNU: {
		title: "login",
		type: ControlType2.Link,
	},
	burzVaCmv: {
		defaultValue: "2024",
		displayTextArea: false,
		title: "year",
		type: ControlType2.String,
	},
});
addFonts2(
	FramerJHOLsHwUh,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Space Grotesk",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/spacegrotesk/v21/V8mQoQDjQSkFtoMM3T6r8E7mF71Q-gOoraIAEj7oUUsmNsFjTDJK.woff2",
					weight: "400",
				},
				{
					family: "Space Grotesk",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/spacegrotesk/v21/V8mQoQDjQSkFtoMM3T6r8E7mF71Q-gOoraIAEj7aUUsmNsFjTDJK.woff2",
					weight: "500",
				},
			],
		},
		...SocialIconFonts,
		...NavItemFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "jwF72UoRb",
	xl: "GDQSlkfkE",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"620e74c088cdcb263f9a9365da4ff5f48d29f3d2d6a08de508a575bfe926dca6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"620e74c088cdcb263f9a9365da4ff5f48d29f3d2d6a08de508a575bfe926dca6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var footer_default = ComponentWithRoot;
export { footer_default as default };
