// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 620e74c088cdcb26 "Unframer Home Page", do not edit manually */
"use client";
import {
  stdin_default
} from "./chunks/chunk-OB6JXTMV.js";

// virtual:logo
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "DUAcI4tN5"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "CDLIDQEFG": { "path": "/contact" }, "augiA20Il": { "path": "/" }, "s69UEbhsF": { "path": "/404" }, "tfaaimH0f": { "path": "/testing" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "620e74c088cdcb263f9a9365da4ff5f48d29f3d2d6a08de508a575bfe926dca6",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "CDLIDQEFG": {
          "path": "/contact"
        },
        "augiA20Il": {
          "path": "/"
        },
        "s69UEbhsF": {
          "path": "/404"
        },
        "tfaaimH0f": {
          "path": "/testing"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "620e74c088cdcb263f9a9365da4ff5f48d29f3d2d6a08de508a575bfe926dca6",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
