// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 620e74c088cdcb26 "Unframer Home Page", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Laptop' | 'Tablet' | 'Mobile' | 'Tablet Open' | 'Mobile Open' // Variant
 * framerPlugin?: string // framerPlugin
}} Props

 */
import {
	Icon,
	stdin_default as stdin_default2,
} from "./chunks/chunk-K6UQ5WSB.js";
import { stdin_default } from "./chunks/chunk-OB6JXTMV.js";
import "./chunks/chunk-BVM6H744.js";
import { routes } from "./chunks/chunk-EZMEJNMO.js";

// virtual:navigation
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/j3JOS1ahfJTnmx8Mh2N4/k0cH5ITDTJ8pJWfpAitt/B03nkV2E9.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	Link,
	SmartComponentScopedContainer,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/5Rc4A3RzO15jP4nzpdGK/WfiHNmASBA7fnb58Gyss/KcSL_pfvh.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var FeatherFonts = getFonts(Icon);
var cycleOrder = ["iAP2FH3x9", "IDm9Bjzb4"];
var serializationHash = "framer-AIwoe";
var variantClassNames = {
	iAP2FH3x9: "framer-v-1ri84p4",
	IDm9Bjzb4: "framer-v-dimqrm",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	Humburger: "iAP2FH3x9",
	x: "IDm9Bjzb4",
};
var getProps = ({ height, id, tap, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		njNJdZBy3: tap !== null && tap !== void 0 ? tap : props.njNJdZBy3,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "iAP2FH3x9",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, njNJdZBy3, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "iAP2FH3x9",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1vty52i = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (njNJdZBy3) {
			const res = await njNJdZBy3(...args);
			if (res === false) return false;
		}
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition}>
					<motion.div
						{...restProps}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1ri84p4",
							className,
							classNames,
						)}
						data-framer-name={"Humburger"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"iAP2FH3x9"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={onTap1vty52i}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								IDm9Bjzb4: {
									"data-framer-name": "x",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<motion.div
								className={"framer-1tu957g-container"}
								layoutDependency={layoutDependency}
								layoutId={"tCFR1Cqhd-container"}
							>
								<Icon
									color={
										"var(--token-b50174c0-f355-49d1-a882-48c9e51b5466, rgb(255, 255, 255))"
									}
									height={"100%"}
									iconSearch={"Home"}
									iconSelection={"menu"}
									id={"tCFR1Cqhd"}
									layoutId={"tCFR1Cqhd"}
									mirrored={false}
									selectByList={true}
									style={{
										height: "100%",
										width: "100%",
									}}
									width={"100%"}
									{...addPropertyOverrides(
										{
											IDm9Bjzb4: {
												iconSelection: "x",
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	'.framer-AIwoe[data-border="true"]::after, .framer-AIwoe [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-AIwoe.framer-12zeeso, .framer-AIwoe .framer-12zeeso { display: block; }",
	".framer-AIwoe.framer-1ri84p4 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 30px; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 30px; }",
	".framer-AIwoe .framer-1tu957g-container { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-AIwoe.framer-1ri84p4 { gap: 0px; } .framer-AIwoe.framer-1ri84p4 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-AIwoe.framer-1ri84p4 > :first-child { margin-left: 0px; } .framer-AIwoe.framer-1ri84p4 > :last-child { margin-right: 0px; } }",
];
var FramerKcSL_pfvh = withCSS(Component, css, "framer-AIwoe");
var stdin_default3 = FramerKcSL_pfvh;
FramerKcSL_pfvh.displayName = "Humburger";
FramerKcSL_pfvh.defaultProps = {
	height: 30,
	width: 30,
};
addPropertyControls(FramerKcSL_pfvh, {
	variant: {
		options: ["iAP2FH3x9", "IDm9Bjzb4"],
		optionTitles: ["Humburger", "x"],
		title: "Variant",
		type: ControlType.Enum,
	},
	njNJdZBy3: {
		title: "Tap",
		type: ControlType.EventHandler,
	},
});
addFonts(FramerKcSL_pfvh, [...FeatherFonts]);

// /:https://framerusercontent.com/modules/j3JOS1ahfJTnmx8Mh2N4/k0cH5ITDTJ8pJWfpAitt/B03nkV2E9.js
var LogoFonts = getFonts2(stdin_default);
var HumburgerFonts = getFonts2(stdin_default3);
var NavItemFonts = getFonts2(stdin_default2);
var cycleOrder2 = [
	"L0DaE_bte",
	"PtaOIcD45",
	"f9fk6Mkyb",
	"FaZIgvlqN",
	"Di1J4ilpy",
	"QOtg04heF",
];
var serializationHash2 = "framer-nivn8";
var variantClassNames2 = {
	Di1J4ilpy: "framer-v-10nb6es",
	f9fk6Mkyb: "framer-v-1g88cgc",
	FaZIgvlqN: "framer-v-1vke8jl",
	L0DaE_bte: "framer-v-x6zt6g",
	PtaOIcD45: "framer-v-1ajgh1c",
	QOtg04heF: "framer-v-hqfqie",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Mobile Open": "QOtg04heF",
	"Tablet Open": "Di1J4ilpy",
	Desktop: "L0DaE_bte",
	Laptop: "PtaOIcD45",
	Mobile: "FaZIgvlqN",
	Tablet: "f9fk6Mkyb",
};
var getProps2 = ({ framerPlugin, height, id, width, ...props }) => {
	return {
		...props,
		J_QbTJlEC: framerPlugin ?? props.J_QbTJlEC,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "L0DaE_bte",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const { style, className, layoutId, variant, J_QbTJlEC, ...restProps } =
		getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "L0DaE_bte",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const njNJdZBy3ca83ep = activeVariantCallback(async (...args) => {
		setVariant("Di1J4ilpy");
	});
	const njNJdZBy31wa68ta = activeVariantCallback(async (...args) => {
		setVariant("QOtg04heF");
	});
	const njNJdZBy31njtunl = activeVariantCallback(async (...args) => {
		setVariant("f9fk6Mkyb");
	});
	const njNJdZBy3vb9rhe = activeVariantCallback(async (...args) => {
		setVariant("FaZIgvlqN");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (
			["f9fk6Mkyb", "FaZIgvlqN", "Di1J4ilpy", "QOtg04heF"].includes(baseVariant)
		)
			return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["f9fk6Mkyb", "FaZIgvlqN"].includes(baseVariant)) return false;
		return true;
	};
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-x6zt6g",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"L0DaE_bte"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								Di1J4ilpy: {
									"data-framer-name": "Tablet Open",
								},
								f9fk6Mkyb: {
									"data-framer-name": "Tablet",
								},
								FaZIgvlqN: {
									"data-framer-name": "Mobile",
								},
								PtaOIcD45: {
									"data-framer-name": "Laptop",
								},
								QOtg04heF: {
									"data-framer-name": "Mobile Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1pn4djv"}
							data-framer-name={"Brand Logo"}
							layoutDependency={layoutDependency}
							layoutId={"GgYYyrvAl"}
						>
							<ComponentViewportProvider2
								height={38}
								y={
									(componentViewport?.y || 0) +
									(22 + ((componentViewport?.height || 82) - 44 - 38) / 2) +
									0
								}
								{...addPropertyOverrides2(
									{
										Di1J4ilpy: {
											y:
												(componentViewport?.y || 0) +
												15 +
												(((componentViewport?.height || 247) - 15 - 231) / 2 +
													0 +
													0) +
												0,
										},
										f9fk6Mkyb: {
											y:
												(componentViewport?.y || 0) +
												15 +
												(((componentViewport?.height || 68) - 30 - 38) / 2 +
													0 +
													0) +
												0,
										},
										FaZIgvlqN: {
											y:
												(componentViewport?.y || 0) +
												15 +
												(((componentViewport?.height || 68) - 30 - 38) / 2 +
													0 +
													0) +
												0,
										},
										QOtg04heF: {
											y:
												(componentViewport?.y || 0) +
												15 +
												(((componentViewport?.height || 223) - 15 - 207) / 2 +
													0 +
													0) +
												0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1vm1wu6-container"}
									layoutDependency={layoutDependency}
									layoutId={"IRk2bPeWN-container"}
									nodeId={"IRk2bPeWN"}
									rendersWithMotion={true}
									scopeId={"B03nkV2E9"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										id: "IRk2bPeWN",
										layoutId: "IRk2bPeWN",
										variant: "DUAcI4tN5",
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider2>
							{isDisplayed() && (
								<motion2.div
									className={"framer-vij12t"}
									data-framer-name={"Button & Burger"}
									layoutDependency={layoutDependency}
									layoutId={"iyNONNBmO"}
									style={{
										borderBottomLeftRadius: 8,
										borderBottomRightRadius: 8,
										borderTopLeftRadius: 8,
										borderTopRightRadius: 8,
									}}
								>
									{isDisplayed() && (
										<ComponentViewportProvider2
											{...addPropertyOverrides2(
												{
													Di1J4ilpy: {
														height: 30,
														width: "30px",
														y:
															(componentViewport?.y || 0) +
															15 +
															(((componentViewport?.height || 247) - 15 - 231) /
																2 +
																0 +
																0) +
															4 +
															0,
													},
													f9fk6Mkyb: {
														height: 30,
														width: "30px",
														y:
															(componentViewport?.y || 0) +
															15 +
															(((componentViewport?.height || 68) - 30 - 38) /
																2 +
																0 +
																0) +
															4 +
															0,
													},
													FaZIgvlqN: {
														height: 30,
														width: "30px",
														y:
															(componentViewport?.y || 0) +
															15 +
															(((componentViewport?.height || 68) - 30 - 38) /
																2 +
																0 +
																0) +
															4 +
															0,
													},
													QOtg04heF: {
														height: 30,
														width: "30px",
														y:
															(componentViewport?.y || 0) +
															15 +
															(((componentViewport?.height || 223) - 15 - 207) /
																2 +
																0 +
																0) +
															4 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-8f3t96-container"}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"DLM5SZLyW-container"}
												nodeId={"DLM5SZLyW"}
												rendersWithMotion={true}
												scopeId={"B03nkV2E9"}
											>
												{_jsx2(stdin_default3, {
													height: "100%",
													id: "DLM5SZLyW",
													layoutId: "DLM5SZLyW",
													style: {
														height: "100%",
														width: "100%",
													},
													variant: "iAP2FH3x9",
													width: "100%",
													...addPropertyOverrides2(
														{
															Di1J4ilpy: {
																njNJdZBy3: njNJdZBy31njtunl,
																variant: "IDm9Bjzb4",
															},
															f9fk6Mkyb: {
																njNJdZBy3: njNJdZBy3ca83ep,
															},
															FaZIgvlqN: {
																njNJdZBy3: njNJdZBy31wa68ta,
															},
															QOtg04heF: {
																njNJdZBy3: njNJdZBy3vb9rhe,
																variant: "IDm9Bjzb4",
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider2>
									)}
								</motion2.div>
							)}
						</motion2.div>
						{isDisplayed1() && (
							<Link
								href={"mailto:tommy@unframer.co"}
								motionChild={true}
								nodeId={"jHaD9HYjR"}
								scopeId={"B03nkV2E9"}
							>
								<motion2.a
									className={"framer-16n4jst framer-ce1ha9"}
									data-framer-name={"Menu"}
									layoutDependency={layoutDependency}
									layoutId={"jHaD9HYjR"}
									style={{
										backgroundColor: "rgba(25, 23, 30, 0)",
									}}
									variants={{
										Di1J4ilpy: {
											backgroundColor:
												"var(--token-4bd7eeba-669e-49ab-85d5-91da45add9b3, rgb(21, 21, 20))",
										},
										QOtg04heF: {
											backgroundColor:
												"var(--token-4bd7eeba-669e-49ab-85d5-91da45add9b3, rgb(21, 21, 20))",
										},
									}}
								>
									<ComponentViewportProvider2
										height={27}
										y={
											(componentViewport?.y || 0) +
											(22 + ((componentViewport?.height || 82) - 44 - 27) / 2) +
											0
										}
										{...addPropertyOverrides2(
											{
												Di1J4ilpy: {
													y:
														(componentViewport?.y || 0) +
														15 +
														(((componentViewport?.height || 247) - 15 - 231) /
															2 +
															38 +
															24) +
														32 +
														0,
												},
												QOtg04heF: {
													y:
														(componentViewport?.y || 0) +
														15 +
														(((componentViewport?.height || 223) - 15 - 207) /
															2 +
															38 +
															24) +
														20 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1lrlu2p-container"}
											layoutDependency={layoutDependency}
											layoutId={"klT79Pe02-container"}
											nodeId={"klT79Pe02"}
											rendersWithMotion={true}
											scopeId={"B03nkV2E9"}
										>
											{_jsx2(stdin_default2, {
												cRqRWoih6: J_QbTJlEC,
												height: "100%",
												id: "klT79Pe02",
												layoutId: "klT79Pe02",
												Oc0fzh3x0: false,
												okFfDCMAr: "React Export Plugin",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider2>
									<ComponentViewportProvider2
										height={27}
										y={
											(componentViewport?.y || 0) +
											(22 + ((componentViewport?.height || 82) - 44 - 27) / 2) +
											0
										}
										{...addPropertyOverrides2(
											{
												Di1J4ilpy: {
													y:
														(componentViewport?.y || 0) +
														15 +
														(((componentViewport?.height || 247) - 15 - 231) /
															2 +
															38 +
															24) +
														32 +
														39,
												},
												QOtg04heF: {
													y:
														(componentViewport?.y || 0) +
														15 +
														(((componentViewport?.height || 223) - 15 - 207) /
															2 +
															38 +
															24) +
														20 +
														39,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-mefznb-container"}
											layoutDependency={layoutDependency}
											layoutId={"di_YH1Zxl-container"}
											nodeId={"di_YH1Zxl"}
											rendersWithMotion={true}
											scopeId={"B03nkV2E9"}
										>
											{_jsx2(stdin_default2, {
												cRqRWoih6: "mailto:tommy@unframer.co",
												height: "100%",
												id: "di_YH1Zxl",
												layoutId: "di_YH1Zxl",
												Oc0fzh3x0: false,
												okFfDCMAr: "Contact",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider2>
									<ComponentViewportProvider2
										height={27}
										y={
											(componentViewport?.y || 0) +
											(22 + ((componentViewport?.height || 82) - 44 - 27) / 2) +
											0
										}
										{...addPropertyOverrides2(
											{
												Di1J4ilpy: {
													y:
														(componentViewport?.y || 0) +
														15 +
														(((componentViewport?.height || 247) - 15 - 231) /
															2 +
															38 +
															24) +
														32 +
														78,
												},
												QOtg04heF: {
													y:
														(componentViewport?.y || 0) +
														15 +
														(((componentViewport?.height || 223) - 15 - 207) /
															2 +
															38 +
															24) +
														20 +
														78,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1a5umnd-container"}
											layoutDependency={layoutDependency}
											layoutId={"yWsmagNMV-container"}
											nodeId={"yWsmagNMV"}
											rendersWithMotion={true}
											scopeId={"B03nkV2E9"}
										>
											{_jsx2(stdin_default2, {
												cRqRWoih6: "/login",
												height: "100%",
												id: "yWsmagNMV",
												layoutId: "yWsmagNMV",
												Oc0fzh3x0: false,
												okFfDCMAr: "Manage Subscription",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider2>
								</motion2.a>
							</Link>
						)}
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-nivn8.framer-ce1ha9, .framer-nivn8 .framer-ce1ha9 { display: block; }",
	".framer-nivn8.framer-x6zt6g { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; padding: 22px 0px 22px 0px; position: relative; width: 1296px; }",
	".framer-nivn8 .framer-1pn4djv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-nivn8 .framer-1vm1wu6-container, .framer-nivn8 .framer-1lrlu2p-container, .framer-nivn8 .framer-mefznb-container, .framer-nivn8 .framer-1a5umnd-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-nivn8 .framer-vij12t { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; min-height: 56px; min-width: 231px; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-nivn8 .framer-8f3t96-container { flex: none; height: 30px; position: relative; width: 30px; }",
	".framer-nivn8 .framer-16n4jst { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; z-index: 6; }",
	".framer-nivn8.framer-v-1ajgh1c.framer-x6zt6g { padding: 22px 30px 22px 30px; width: 1000px; }",
	".framer-nivn8.framer-v-1ajgh1c .framer-16n4jst { gap: 27px; }",
	".framer-nivn8.framer-v-1g88cgc.framer-x6zt6g { flex-direction: column; gap: 24px; justify-content: center; padding: 15px 30px 15px 30px; width: 810px; }",
	".framer-nivn8.framer-v-1g88cgc .framer-1pn4djv, .framer-nivn8.framer-v-1vke8jl .framer-1pn4djv, .framer-nivn8.framer-v-10nb6es .framer-1pn4djv { gap: unset; justify-content: space-between; width: 100%; }",
	".framer-nivn8.framer-v-1g88cgc .framer-vij12t, .framer-nivn8.framer-v-1vke8jl .framer-vij12t, .framer-nivn8.framer-v-10nb6es .framer-vij12t, .framer-nivn8.framer-v-hqfqie .framer-vij12t { min-height: unset; min-width: unset; }",
	".framer-nivn8.framer-v-1vke8jl.framer-x6zt6g { flex-direction: column; gap: 24px; justify-content: center; padding: 15px 20px 15px 20px; width: 527px; }",
	".framer-nivn8.framer-v-10nb6es.framer-x6zt6g { flex-direction: column; gap: 24px; justify-content: center; padding: 15px 30px 0px 30px; width: 810px; }",
	".framer-nivn8.framer-v-10nb6es .framer-16n4jst { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 12px; padding: 32px; width: 108%; z-index: 1; }",
	".framer-nivn8.framer-v-hqfqie.framer-x6zt6g { flex-direction: column; gap: 24px; justify-content: center; padding: 15px 0px 0px 0px; width: 390px; }",
	".framer-nivn8.framer-v-hqfqie .framer-1pn4djv { gap: unset; justify-content: space-between; padding: 0px 20px 0px 20px; width: 100%; }",
	".framer-nivn8.framer-v-hqfqie .framer-16n4jst { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 12px; padding: 20px 15px 20px 15px; width: 100%; z-index: 1; }",
];
var FramerB03nkV2E9 = withCSS2(Component2, css2, "framer-nivn8");
var stdin_default4 = FramerB03nkV2E9;
FramerB03nkV2E9.displayName = "Navigation";
FramerB03nkV2E9.defaultProps = {
	height: 82,
	width: 1296,
};
addPropertyControls2(FramerB03nkV2E9, {
	variant: {
		options: [
			"L0DaE_bte",
			"PtaOIcD45",
			"f9fk6Mkyb",
			"FaZIgvlqN",
			"Di1J4ilpy",
			"QOtg04heF",
		],
		optionTitles: [
			"Desktop",
			"Laptop",
			"Tablet",
			"Mobile",
			"Tablet Open",
			"Mobile Open",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
	J_QbTJlEC: {
		title: "framerPlugin",
		type: ControlType2.Link,
	},
});
addFonts2(
	FramerB03nkV2E9,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LogoFonts,
		...HumburgerFonts,
		...NavItemFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "f9fk6Mkyb",
	xl: "L0DaE_bte",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"620e74c088cdcb263f9a9365da4ff5f48d29f3d2d6a08de508a575bfe926dca6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavigationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"620e74c088cdcb263f9a9365da4ff5f48d29f3d2d6a08de508a575bfe926dca6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var navigation_default = ComponentWithRoot;
export { navigation_default as default };
