openapi: 3.1.3
info:
  title: Spiceflow Documentation
  description: Development documentation
  version: 0.0.0
paths:
  /api/plugins/currentOrg:
    post:
      operationId: postApiPluginsCurrentOrg
  /api/plugins/getSessionForKey:
    post:
      parameters: []
      operationId: postApiPluginsGetSessionForKey
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                projectId:
                  type: string
              additionalProperties: false
              $schema: http://json-schema.org/draft-07/schema#
  /api/plugins/health:
    get:
      responses:
        '200':
          $schema: http://json-schema.org/draft-07/schema#
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                required:
                  - ok
      operationId: getApiPluginsHealth
  /api/plugins/sse-test:
    get:
      operationId: getApiPluginsSse-test
  /api/plugins/errorExample:
    get:
      responses:
        '200':
          $schema: http://json-schema.org/draft-07/schema#
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                required:
                  - ok
      operationId: getApiPluginsErrorExample
  /api/plugins/openapi:
    get:
      operationId: getApiPluginsOpenapi
  /api/plugins/rewritePlugin/submitReview:
    post:
      parameters: []
      operationId: postApiPluginsRewritePluginSubmitReview
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                stars:
                  type: integer
                  minimum: 1
                  maximum: 5
                generationId:
                  type: integer
                  exclusiveMinimum: 0
              required:
                - stars
                - generationId
              additionalProperties: false
              $schema: http://json-schema.org/draft-07/schema#
  /api/plugins/rewritePlugin/rephrase:
    post:
      parameters: []
      operationId: postApiPluginsRewritePluginRephrase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  anyOf:
                    - anyOf:
                        - not: {}
                        - type: string
                    - type: 'null'
                oldText: {}
                sourceHtml:
                  type:
                    - string
                    - 'null'
                url:
                  type: string
                projectName:
                  type: string
                pagePath:
                  type: string
              required:
                - sourceHtml
                - url
              additionalProperties: false
              $schema: http://json-schema.org/draft-07/schema#
  /api/plugins/rewritePlugin/discardGeneration:
    post:
      parameters: []
      operationId: postApiPluginsRewritePluginDiscardGeneration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
              required:
                - id
              additionalProperties: false
              $schema: http://json-schema.org/draft-07/schema#
  /api/plugins/rewritePlugin/getCredits:
    post:
      operationId: postApiPluginsRewritePluginGetCredits
  /api/plugins/rewritePlugin/activateLicense:
    post:
      parameters: []
      operationId: postApiPluginsRewritePluginActivateLicense
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                licenseKey:
                  type: string
              required:
                - licenseKey
              additionalProperties: false
              $schema: http://json-schema.org/draft-07/schema#
  /api/plugins/rewritePlugin/getWebsiteHtml:
    post:
      parameters: []
      operationId: postApiPluginsRewritePluginGetWebsiteHtml
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                domain:
                  type: string
              required:
                - domain
              additionalProperties: false
              $schema: http://json-schema.org/draft-07/schema#
  /api/plugins/markdownPlugin/health:
    get:
      operationId: getApiPluginsMarkdownPluginHealth
  /api/plugins/markdownPlugin/githubRepoList:
    post:
      parameters: []
      operationId: postApiPluginsMarkdownPluginGithubRepoList
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                githubAccountLogin:
                  type: string
                  minLength: 1
              required:
                - githubAccountLogin
              additionalProperties: false
              $schema: http://json-schema.org/draft-07/schema#
  /api/plugins/markdownPlugin/syncsThisMonth:
    post:
      parameters: []
      operationId: postApiPluginsMarkdownPluginSyncsThisMonth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projectId:
                  type: string
                projectName:
                  type: string
              additionalProperties: false
              $schema: http://json-schema.org/draft-07/schema#
  /api/plugins/markdownPlugin/subscriptions:
    get:
      parameters:
        - schema:
            type: string
          in: query
          name: projectId
          required: false
      operationId: getApiPluginsMarkdownPluginSubscriptions
  /api/plugins/markdownPlugin/frontmatter:
    post:
      parameters: []
      operationId: postApiPluginsMarkdownPluginFrontmatter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                owner:
                  type: string
                repo:
                  type: string
                basePath:
                  type: string
                githubAccountLogin:
                  type: string
              required:
                - owner
                - repo
                - basePath
                - githubAccountLogin
              additionalProperties: false
              $schema: http://json-schema.org/draft-07/schema#
  /api/plugins/markdownPlugin/syncGithub:
    post:
      parameters: []
      operationId: postApiPluginsMarkdownPluginSyncGithub
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                itemIds:
                  type: array
                  items:
                    type: string
                owner:
                  type: string
                repo:
                  type: string
                basePath:
                  type: string
                githubAccountLogin:
                  type: string
                projectId:
                  type: string
                projectName:
                  type: string
                mapFieldsConfig: {}
                onlyGetFrontmatter:
                  type: boolean
                enablePartialUpdate:
                  type: boolean
              required:
                - owner
                - repo
                - basePath
                - githubAccountLogin
                - projectId
                - projectName
              additionalProperties: false
              $schema: http://json-schema.org/draft-07/schema#
  /api/plugins/markdownPlugin/checkBasePath:
    post:
      parameters: []
      operationId: postApiPluginsMarkdownPluginCheckBasePath
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                owner:
                  type: string
                repo:
                  type: string
                basePath:
                  type: string
                githubAccountLogin:
                  type: string
              required:
                - owner
                - repo
                - basePath
                - githubAccountLogin
              additionalProperties: false
              $schema: http://json-schema.org/draft-07/schema#
  /api/plugins/reactExportPlugin/health:
    get:
      operationId: getApiPluginsReactExportPluginHealth
  /api/plugins/reactExportPlugin/project/{projectId}:
    get:
      operationId: getApiPluginsReactExportPluginProjectByProjectId
  /api/plugins/reactExportPlugin/subscriptions:
    get:
      parameters:
        - schema:
            type: string
          in: query
          name: projectId
          required: true
      operationId: getApiPluginsReactExportPluginSubscriptions
  /api/plugins/reactExportPlugin/upsertProject:
    post:
      parameters: []
      operationId: postApiPluginsReactExportPluginUpsertProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                components:
                  type: array
                pages:
                  type: array
                projectId:
                  type: string
                projectName:
                  type: string
                colorStyles:
                  type: array
              required:
                - components
                - projectId
                - colorStyles
              additionalProperties: false
              $schema: http://json-schema.org/draft-07/schema#
components:
  schemas: {}
