openapi: 3.1.3
info:
  title: Spiceflow Documentation
  description: Development documentation
  version: 0.0.0
paths:
  /api/plugins/angledScreen/generationsForUser:
    get:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/angledScreen/incrementGenerations:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/angledScreen/activate:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/currentOrg:
    post:
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/getSessionForKey:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/health:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/sse-test:
    get:
      x-fern-streaming:
        format: sse
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/errorExample:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/validateSession:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/openapi:
    get:
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/rewritePlugin/submitReview:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/rewritePlugin/rephrase:
    post:
      x-fern-streaming:
        format: sse
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/rewritePlugin/discardGeneration:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/rewritePlugin/getCredits:
    post:
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/rewritePlugin/getWebsiteHtml:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/markdownPlugin/health:
    get:
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/markdownPlugin/githubRepoList:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/markdownPlugin/syncsThisMonth:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/markdownPlugin/subscriptions:
    get:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/markdownPlugin/frontmatter:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/markdownPlugin/syncGithub:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/markdownPlugin/checkBasePath:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/reactExportPlugin/health:
    get:
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/reactExportPlugin/project/{projectId}:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: projectId
          required: true
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/reactExportPlugin/project/{projectId}/publish:
    post:
      parameters:
        - schema:
            type: string
          in: path
          name: projectId
          required: true
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/reactExportPlugin/project/{projectId}/subscribe:
    get:
      x-fern-streaming:
        format: sse
      parameters:
        - schema:
            type: string
          in: path
          name: projectId
          required: true
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/reactExportPlugin/subscriptions:
    get:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/reactExportPlugin/upsertUnframerRepoWithAI:
    post:
      x-fern-streaming:
        format: sse
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/reactExportPlugin/upsertProject:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/llm/health:
    get:
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/llm/submitReview:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/llm/publish:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/llm/getCredits:
    post:
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/plugins/llm/generate:
    post:
      x-fern-streaming:
        format: sse
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
  /api/plugins/llm/subscriptions:
    get:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
components:
  schemas: {}
